name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Lint and Test
        run: npm test
      - name: Build and Pack
        run: |
          npm run build
          RELEASENAME=$(npm pack)
          mv $RELEASENAME release.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.tgz
          prerelease: ${{ true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}