name: Create Release

env:
  NODE_VERSION: 22.4.x

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run Format Checker
        run: npm run check:format
        working-directory: ./
        timeout-minutes: 10
      - name: Lint
        run: npm run lint
      - name: Build, Test and Pack
        run: |
          npm run build
          npm run testcoverage
          RELEASENAME=$(npm pack)
          mv $RELEASENAME release.tgz
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.tgz
          prerelease: ${{ contains(github.ref, '-') }} # If tag contains -, it's a prerelease (e.g. /refs/tags/v8.30.0-0)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
