name: Trigger Release Creation

on:
  workflow_dispatch:
    inputs:
      prassignee:
        description: "User to assign PR to (defaults to current user)"
        required: false
        type: string
      isfinalreleasebuild:
        description: "Build final release build? (if unchecked, this builds a pre-release)"
        required: true
        type: boolean
        default: false

env:
  NODE_VERSION: 22

jobs:
  configure:
    name: Configure Release Branch
    runs-on: ubuntu-latest
    env:
      isprereleasebuild: ${{ inputs.isfinalreleasebuild != true }}
      prassignee: ${{ inputs.prassignee || github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master
          token: ${{ secrets.DEVBOT_GH_TOKEN }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Configure Git
        run: |
          git config user.name 'Development Bot'
          git config user.email 'devbot@roxtra.com'
      - name: Install dependencies
        run: npm ci
      - id: version-upgrade
        name: Upgrade Version
        # Make next RC Final or create pre-release based on chosen variant
        run: |
          if ${{ env.isprereleasebuild }}; then npm version prerelease; else npm version minor; fi
          NEWVERSION=$(echo "console.log(require('./package.json').version);" | node)
          echo "newversion=$(echo $NEWVERSION)" >> $GITHUB_OUTPUT
      - name: Create Branch and Push Branch and Tag
        run: |
          echo "Create Release Branch"
          git checkout -b release-v${{ steps.version-upgrade.outputs.newversion }}
      - name: Bump Version to next RC
        # Only bump version to next RC if release is non-prerelease
        if: ${{ env.isprereleasebuild == 'false' }}
        run: |
          echo "Bump Version to next RC"
          npm version --git-tag-version false preminor
          git commit -a -m "Bump RC Version"
      - name: Push Branch and Tag
        run: |
          echo "Push branch and tag"
          git push -u origin release-v${{ steps.version-upgrade.outputs.newversion }}
          git push origin v${{ steps.version-upgrade.outputs.newversion }}
      - name: Create PR for new Version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base master --head release-v${{ steps.version-upgrade.outputs.newversion }} --title "Release v${{ steps.version-upgrade.outputs.newversion }}" --body "Updates version to v${{ steps.version-upgrade.outputs.newversion }}" --assignee "${{ env.prassignee }}"
